//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicesUsersEx.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class usuariosExEntities2 : DbContext
    {
        public usuariosExEntities2()
            : base("name=usuariosExEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alquilado> Alquiladoes { get; set; }
        public virtual DbSet<Propio> Propios { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
