//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicesUsersEx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propio
    {
        public string User { get; set; }
        public string Serial_ { get; set; }
        public string PC_Name { get; set; }
        public Nullable<System.DateTime> Installation_Date { get; set; }
        public string Specifications_ { get; set; }
        public string Ram { get; set; }
        public string Desktop_Laptop { get; set; }
        public string Domain { get; set; }
        public int Id { get; set; }
    }
}
